name: Build, Test, and Publish

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      # Add version calculation step
      - name: Calculate version
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        id: calculate_version
        run: |
          # Get the latest tag
          latest_tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          
          # Extract version numbers
          IFS='.' read -r major minor patch <<< "${latest_tag#v}"
          
          # Increment minor version
          new_minor=$((minor + 1))
          new_version="v$major.$new_minor.0"
          
          echo "New version will be: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Update version in build files
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: |
          new_version=${{ steps.calculate_version.outputs.new_version }}
          # Remove 'v' prefix for gradle version
          gradle_version=${new_version#v}
          
          # Update version in lib/build.gradle.kts
          if [ -f "lib/build.gradle.kts" ]; then
            sed -i "s/version = \".*\"/version = \"$gradle_version\"/" lib/build.gradle.kts
          fi
          
          # Update version in gradle.properties if it exists
          if [ -f "gradle.properties" ]; then
            sed -i "s/^version=.*/version=$gradle_version/" gradle.properties
          fi
          
          # Update version in libs.versions.toml if it exists
          if [ -f "gradle/libs.versions.toml" ]; then
            sed -i "s/^version = \".*\"/version = \"$gradle_version\"/" gradle/libs.versions.toml
          fi

      - name: Build with Gradle
        run: ./gradlew build

      - name: Test with Gradle
        run: ./gradlew test jacocoTestReport

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/coverage/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: build/reports/jacoco/test/jacocoTestReport.xml
          fail_ci_if_error: true

      - name: Sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew sonar --info

      - name: Publish to GitHub Packages
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: ./gradlew publish

      # Create GitHub Release
      - name: Create Release
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.calculate_version.outputs.new_version }}
          release_name: Release ${{ steps.calculate_version.outputs.new_version }}
          draft: false
          prerelease: false
          body: |
            Automated release for version ${{ steps.calculate_version.outputs.new_version }}
            
            ### What's Changed
            * Automated release from master branch
            * For detailed changes, please check the [commit history](https://github.com/${{ github.repository }}/commits/master)

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: lib/build/libs